name: Workflow push
on: push
jobs:
  test:
    name: Mon premier test
    runs-on: ubuntu-latest
    steps:
      - name: récupérer le code
        uses: actions/checkout@v4
      - name: install
        run: npm install
      - name: build
        run: npm run build
      - name: Upload le résultat du build
        uses: actions/upload-artifact@v4
        with:
          name: mon-site
          path: .next/

