name: Workflow push
on: push
jobs:
  test:
    name: Mon premier test
    runs-on: ubuntu-latest
    steps:
      - name: install
        run: npm installnpm install
      - name: start
        run: npm start

